### ISSUE TITLE
Sprinkler search test can make a lot of requests in the setup (135+ on HAPI)

### ISSUE THREAD

**Issue by arscan** [fhir-crucible/plan_executor#126]
I'm not sure if this is something we really want to be doing or is useful...

![screen shot 2017-03-07 at 1 07 08 pm](https://cloud.githubusercontent.com/assets/412901/23670905/4ff47942-0337-11e7-8b1f-68267aeec51a.png)

**Comment by jawalonoski** [comment]
You have to know how many things there are before you can check whether or not the counts are right.

Is there a better idea?

**Comment by arscan** [comment]
Ah true, I didn't even read through the test.  Crucible currently can't support showing 135 requests because it will crash the browser while trying to pretty-print the json/xml.  Plus, this will cause our db to balloon at a much faster rate.  I suppose we have three options:

1) scrap recording and showng setup/teardown requests (which I feel is bad because that is needed to debug)
2) keep recording, live with the balooning db, and fix the UI somehow so it can show all those requests without crashing browsers
3) rewrite test to somehow limit the number of requests.  Like just grab the first few bundles, and then make sure there are at least as many hits as you see in the bundles, since there could be more.

**Comment by arscan** [comment]
I just checked it out -- the setup requests from HAPI on that test are ~8 megs.  The whole rest of the test comes to 1/2 meg.  So a 16x increase in storage size for that test.

**Comment by arscan** [comment]
Fixed in https://github.com/fhir-crucible/plan_executor/pull/129.  I ended up allowing tests to 'mute' requests using a block if it knows there will be a lot of them that will have little value in debugging.
