### ISSUE TITLE
X030_DeviceRequest intermittently fails

### ISSUE THREAD

**Issue by brendankowitz** [fhir-crucible/plan_executor#136]
This can be seen on the Crucible server: https://www.projectcrucible.org/servers/593a8f8e63727513d6020000#5a3af9fe04ebd03841000000/resourcetest_devicerequest/X030_DeviceRequest

This test sometimes fails due to generating an invalid request, the error message (from the FHIR test server) is:
```
DeviceRequest, Element "DeviceRequest.code[x]" (DeviceRequest.code[x]): minimum required = 1, but only found 0
```

When the test is re-run, sometimes a code will be sent, which passes.

Ref: https://github.com/fhir-crucible/plan_executor/blob/master/lib/tests/suites/resource_test.rb#L225

**Comment by jawalonoski** [comment]
Found the cause of the error... If the `DeviceRequest` has a `codeCodeableConcept` then everything works fine, but if the `DeviceRequest` has a `codeReference` then it gets deleted before the update and it sends an invalid resource. I'll look into where that is happening.
