### ISSUE TITLE
X010: Subscription: Create New

### ISSUE THREAD

**Issue by jamesagnew** [fhir-crucible/plan_executor#49]
This test creates a subscription with criteria `<criteria value="5OZ3cHdGHZ8yxDPkwqtxqQ=="/>`, but this criteria does not make sense and should presumably be rejected by any server that actually plans on honoring the subscription (as HAPI is doing).

**Comment by jawalonoski** [comment]
Thanks for the bug report. We have a number of issues like this across the X010 series of tests for various resources that we're working on. I've fixed this particular issue, and we'll continue to strengthen our resource generation.

**Comment by jamesagnew** [comment]
Cool, thanks @jawalonoski ! 

I can only imagine how hard it must be to keep a complete set of tests for all of FHIR.. :) I'll report these as I find 'em
