### ISSUE TITLE
FHIR Testing Match Conformance/Interoperability tests between Capability Statement and FHIR Published Specifications

### ISSUE THREAD

**Issue by Interopguy** [fhir-crucible/plan_executor#95]
As a FHIR Server I am required by FHIR Specifications to publically publish a Capability (formerly Conformance) Statement - in accordance with the FHIR Specification the Capability Statement (http://hl7.org/fhir/2017Jan/capabilitystatement.html) includes an element fhirVersion (http://hl7.org/fhir/2017Jan/capabilitystatement-definitions.html#CapabilityStatement.fhirVersion) - valid published FHIR Version(s) are viewable here - http://hl7.org/fhir/directory.html 

(#1) As a FHIR Server I would like Crucible to identify and ensure the Server fhirVersion is actively part of the test cases chosen and are specific to the published version of FHIR being tested.  Note: FHIR Version STU 3 Candidate or Ballot currently has available four valid published version(s) - with active systems running 1.4.0, 1.6.0 and now 1.8.0 coming online daily.

(#2) As a FHIR Server I would like Crucible to identify which version of FHIR test cases (suite) were used to test my server. e.g. Dec 6, 2016 build 1.8.0 FHIR STU3 Candidate + Connectathon 14 (San Antonio) 

(#3) Please ensure Crucible does NOT publically publish test results where active public servers running a valid version of FHIR are being tested against none compatible published standards - that would represent erroneous reporting by Crucible (could potentially introduce harm to the Organization being reported against).  Given our proximity to HIMSS 2017 - a number of Organizations are planning very high profile FHIR announcements (accurate reporting by public test platforms will be critical to the healthcare marketplace, the industry and HL7). 

e.g. AEGIS WildFHIR (URL - http://wildfhir.aegis.net/fhir1-6-0) self identifies as a FHIR 1.6.0 implementation, and should only be tested against FHIR STU3 version 1.6.0 Baltimore Connectathon profile.  If the Crucible Team updates the public version of Crucible to support/test 1.8.0 - please ensure testing of 1.8.0 occurs only against AEGIS WildFHIR (URL - http://wildfhir.aegis.net/fhir1-8-0) self identifies as a FHIR 1.8.0.

This notes that there are significant and breaking changes being published between the various STU3 versions.  This conversation will be posted to Zulip for more feedback

**Comment by jawalonoski** [comment]
Rob, see #97.

**Comment by jawalonoski** [comment]
Pull requests on fhir-crucible/crucible#211 and fhir-crucible/crucible#212 should address and close both #97 and #95

**Comment by jawalonoski** [comment]
Crucible only displays results from the latest version of FHIR. If someone chooses to test an older version, we allow the test to run, but results are not reported on the homepage.
